// FAQ 单一数据源：首页预览、/faq 页、FAQPage JSON-LD 共用。
export const FAQS: { q: string; a: string }[] = [
  {
    q: "How does it work?",
    a: "Type what you want — a renaissance painting, a Christmas card, your cat as an astronaut — and attach a photo of your pet. Our AI writes the perfect prompt from your words, then paints a new picture that keeps your pet's face, fur and eyes. It takes about half a minute.",
  },
  {
    q: "Will it still look like my pet?",
    a: "Yes — that's the whole point. One clear, face-on photo is enough to start; adding one or two extra angles (a side view, a sitting pose) makes the face and fur even more consistent. We don't promise every portrait is pixel-perfect, but it should always read as your pet.",
  },
  {
    q: "What kind of photos should I upload?",
    a: "Up to 4 photos, JPG/PNG/WebP, each under 5 MB. Best results: your pet alone in the frame, face visible, in good light. No people in the photo, please — the picture is for pets only.",
  },
  {
    q: "What can I ask for in the chat box?",
    a: "Anything: a scene, an outfit, an art style, a mood — or pick one of our 100 ready-made templates and just add your twist. Keep requests about your pet; requests involving people or unsafe content are filtered out.",
  },
  {
    q: "Is it free? How many pictures can I make?",
    a: "You can make a handful of pictures every day for free — no account needed. When you hit the daily limit it resets the next day. Paid plans with more volume are coming soon.",
  },
  {
    q: "Are these images really AI-generated?",
    a: "Yes, 100%. Every picture is generated by an AI image model from the photos you upload. We label it honestly everywhere, and we ask you not to present AI portraits as unedited photographs. See our AI disclosure page for details.",
  },
  {
    q: "What happens to my photos?",
    a: "Your photos are used only to generate your picture. They're not sold, not used to train models, and uploads are automatically deleted within 7 days. You can publish a result to the public gallery yourself — that's always opt-in.",
  },
  {
    q: "Can I use the pictures commercially or as a gift?",
    a: "Yes — print them on cards, post them on social media, gift them to family. The pictures are yours to enjoy. Just keep the AI-generated labeling when you share, and don't use them to mislead (e.g. presenting a pet as a competition winner).",
  },
  {
    q: "Can I make pictures of someone else's pet or a person?",
    a: "Only upload pets you have the rights to. The generator is built for animals — it won't draw humans, and mixing other people's pets into requests isn't allowed.",
  },
  {
    q: "Why does a generation sometimes fail or look off?",
    a: "AI painting is a live service — the studio can hiccup under load, and tricky photos (blurry, dark, multiple pets) can confuse the result. Just try again, ideally with a clearer photo. Regenerating is free and usually fixes it.",
  },
];
