import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";
import { pageMeta } from "@/lib/seo";
import { SITE_MAIL, SITE_NAME, SITE_URL } from "@/lib/site";

export const metadata: Metadata = pageMeta({
  title: "Terms of service",
  description: `The rules for using ${SITE_NAME}: what you may upload, what you may do with the AI pictures, and the common sense we expect.`,
  path: "/terms",
});

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of service"
      intro={`Welcome! These terms govern your use of ${SITE_URL}. By using the site you agree to them.`}
      mail={SITE_MAIL}
      blocks={[
        {
          h: "The service",
          body: [
            `${SITE_NAME} turns a photo of your pet into an AI-generated picture. You can make up to 3 pictures per day for free (we may change this limit; the current rules are always shown in the product). Generating needs no account; downloading pictures requires signing in with Google.`,
          ],
        },
        {
          h: "Your account",
          body: [
            `Sign-in uses Google OAuth — we receive your name, email and profile picture and store a signed session cookie for 30 days. You are responsible for your Google account. You can sign out anytime; signing back in restores access to downloads.`,
          ],
        },
        {
          h: "What you may upload",
          body: [
            `Only photos of pets you own or have permission to use. No people, no photos of children, nothing illegal, harmful, hateful or explicit. We filter requests automatically and can refuse or remove anything that breaks these terms.`,
          ],
        },
        {
          h: "The pictures we make",
          body: [
            `Results are generated by AI and are provided as-is: we can't promise a specific likeness or artistic result. You may use your generated pictures for personal purposes — share them, print them, gift them. Don't present an AI image as an unedited photograph, and don't use generated pictures to mislead, defame, or impersonate.`,
          ],
        },
        {
          h: "The gallery",
          body: [
            `Posting to the public gallery is voluntary. When you submit, you confirm the picture is your creation from your own photo, and you give us permission to display it on the site. You can ask us to remove it anytime.`,
          ],
        },
        {
          h: "Disclaimers & liability",
          body: [
            `The service is provided "as is" without warranties. To the maximum extent permitted by law, we are not liable for indirect or consequential damages. We may pause or change the service for maintenance or improvement.`,
          ],
        },
        {
          h: "Contact & governing law",
          body: [
            `Questions: ${SITE_MAIL}. These terms are governed by the laws of the operator's place of business, without prejudice to mandatory consumer protections in your country of residence.`,
          ],
        },
      ]}
    />
  );
}
